### ISSUE TITLE
The three key parts of the app are 1) do something 2) look at something done and 3) spend my bucks 

### ISSUE THREAD

**Issue by spalsson** [mschmulen/simpleApp13#13]
Can we add a bottom bar that has those 3 buttons.  all apps have these at the bottom with icons

1) Do something -> this take you to the screen with 3 rows and they have a horizontal scroll 

2) look at something done --> this take you to a vertical scroll with the newest "finished action" on the top and you can look at everything old below.  You can comment on each one and maybe hit heart or thumbs up.  Parents can approve to confirm the kids get the bucks

3) this is the store. 10 squares and you can spend yo bucks 

![IMG_0989](https://user-images.githubusercontent.com/13853802/90178206-32b53200-dd71-11ea-87aa-80a8b9dcdc84.png)

**Comment by mschmulen** [comment]
Cool, first pass in build 19

**Comment by mschmulen** [comment]
@spalsson I think this can be closed as a first pass ?

**Comment by spalsson** [comment]
Yup, looks great
