### ISSUE TITLE
Family tab - can we have the newest picture on top

### ISSUE THREAD

**Issue by spalsson** [mschmulen/simpleApp13#20]
in the family tab that has all the pictures in a vertical scroll can we make the newest on top, right now its oldest

**Comment by mschmulen** [comment]
ok so Im going to make an assumption on this that its the most recently updated ... not the most recently created ... so Im going to implement most recently updated as they may have created it some time ago but they may have been rejected and submitted a new one and you want to show them by recently updated.

**Comment by spalsson** [comment]
yup!

**Comment by mschmulen** [comment]
fixed in build 33

**Comment by spalsson** [comment]
All done
