### ISSUE TITLE
show kids "bucks" on Kid main screen 

### ISSUE THREAD

**Issue by mschmulen** [mschmulen/simpleApp13#3]
show kids "bucks" on Kid main screen 
<img width="488" alt="bucks" src="https://user-images.githubusercontent.com/484065/89949200-27d19480-dbed-11ea-9f57-191c7354b68d.png">

**Comment by mschmulen** [comment]
Resolved build 19

**Comment by mschmulen** [comment]
![image](https://user-images.githubusercontent.com/484065/90638786-6077fc00-e1f3-11ea-9ae8-e5b5f5212039.png)

**Comment by spalsson** [comment]
Looks awesome
