### ISSUE TITLE
Every card needs a chat session associated with that card 

### ISSUE THREAD

**Issue by mschmulen** [mschmulen/simpleApp13#6]
Every card needs a chat group associated with that card 
- data model to support a chat group
- update chat feature to support specific chat "room"'s with a card reference
- everyone can see and contribute to the chats 
- investigate notifications + deep-linking

**Comment by mschmulen** [comment]
fixed in the development env and at the CKModel layer. still needs to have representation at the card level

**Comment by mschmulen** [comment]
progress ... card shows the global chat, next step is to implement "chat session" so each card can have its own.

**Comment by spalsson** [comment]
I see the chat world as @mschmulen 

1) global chat - chat everyone and anyone
2) chat on a card - complete a card it might auto reply "done!" and anyone can have a convo on the card.
3) chat as a way to complete a card - chat with grandma or someone for points) (v2 is video chat or sending audio chats)

The complexities are 

1) how do we notify users and deeplink back to the chat.  I chat to oly and when he replies does it notify me and i click and it brings me back to the chat.
2) can we @ people in chats to send them a note specifically 
3) can we add rich media into the chats
